# Form implementation generated from reading ui file '.\Editor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Editor_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 600)
        Form.setStyleSheet("QWidget\n"
"{\n"
"background-color:yellow;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"background-color:white;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color:white;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#dfdfdf;\n"
"}")
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 581, 531))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_save_file = QtWidgets.QPushButton(parent=Form)
        self.pushButton_save_file.setGeometry(QtCore.QRect(10, 553, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_save_file.setFont(font)
        self.pushButton_save_file.setObjectName("pushButton_save_file")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dosya Düzenle"))
        self.pushButton_save_file.setText(_translate("Form", "Kaydet"))
